# Generated by Django 5.1.5 on 2025-04-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_leaverequeststudent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequeststudent',
            name='date_applied',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
