# Generated by Django 5.1.5 on 2025-04-24 09:55

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0009_userprofile_role'),
        ('students', '0005_stureportcard'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stureportcard',
            name='academic_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.academicsession'),
        ),
        migrations.AddField(
            model_name='stureportcard',
            name='address',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='stureportcard',
            name='admission_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='stureportcard',
            name='date',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='stureportcard',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stureportcard',
            name='father_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='stureportcard',
            name='mother_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='stureportcard',
            name='overall_grade',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AddField(
            model_name='stureportcard',
            name='overall_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stureportcard',
            name='overall_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stureportcard',
            name='roll_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='stureportcard',
            name='section',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='stureportcard',
            name='signature_class_teacher',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='stureportcard',
            name='signature_principal',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='stureportcard',
            name='term',
            field=models.CharField(choices=[('Term I', 'Term I'), ('Term II', 'Term II')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='stureportcard',
            name='comments',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='stureportcard',
            name='student',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
