# Generated by Django 5.1.5 on 2025-04-17 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0008_rename_emailaddress_userprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('principal', 'Principal'), ('teacher', 'Teacher'), ('student', 'Student')], default='', max_length=10),
        ),
    ]
